name: Rolling RHEL Binary Build
on:
  workflow_dispatch:
    branches:
      - main
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  schedule:
    # Run every day to detect flakiness and broken dependencies
    - cron: '03 1 * * *'


jobs:
  rolling_rhel_binary:
    name: Rolling RHEL binary build
    runs-on: ubuntu-latest
    env:
      ROS_DISTRO: rolling
    container: ghcr.io/ros-controls/ros:rolling-rhel
    steps:
      - uses: actions/checkout@v3
        with:
          path: src/picknik_controllers
      - run: |
          rosdep update
          rosdep install -iy --from-path src/picknik_controllers
          source /opt/ros/${{ env.ROS_DISTRO }}/setup.bash
          colcon build
          colcon test
